apps/workbench/config/routes.rb
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

ArvadosWorkbench::Application.routes.draw do
  themes_for_rails

  resources :keep_disks
  resources :keep_services
  resources :user_agreements do
    post 'sign', on: :collection
    get 'signatures', on: :collection
  end
  get '/user_agreements/signatures' => 'user_agreements#signatures'
  get "users/setup_popup" => 'users#setup_popup', :as => :setup_user_popup
  get "users/setup" => 'users#setup', :as => :setup_user
  get "report_issue_popup" => 'actions#report_issue_popup', :as => :report_issue_popup
  post "report_issue" => 'actions#report_issue', :as => :report_issue
  get "star" => 'actions#star', :as => :star
  get "all_processes" => 'work_units#index', :as => :all_processes
  get "choose_work_unit_templates" => 'work_unit_templates#choose', :as => :choose_work_unit_templates
  resources :work_units do
    post 'show_child_component', :on => :member
  end
  resources :nodes
  resources :humans
  resources :traits
  resources :api_client_authorizations
  resources :virtual_machines
  resources :containers
  resources :container_requests do
    post 'cancel', :on => :member
    post 'copy', on: :member
  end
  get '/virtual_machines/:id/webshell/:login' => 'virtual_machines#webshell', :as => :webshell_virtual_machine
  resources :authorized_keys
  resources :job_tasks
  resources :jobs do
    post 'cancel', :on => :member
    get 'logs', :on => :member
  end
  resources :repositories do
    post 'share_with', on: :member
  end
  # {format: false} prevents rails from treating "foo.png" as foo?format=png
  get '/repositories/:id/tree/:commit' => 'repositories#show_tree'
  get '/repositories/:id/tree/:commit/*path' => 'repositories#show_tree', as: :show_repository_tree, format: false
  get '/repositories/:id/blob/:commit/*path' => 'repositories#show_blob', as: :show_repository_blob, format: false
  get '/repositories/:id/commit/:commit' => 'repositories#show_commit', as: :show_repository_commit
  resources :sessions
  match '/logout' => 'sessions#destroy', via: [:get, :post]
  get '/logged_out' => 'sessions#logged_out'
  resources :users do
    get 'choose', :on => :collection
    get 'home', :on => :member
    get 'welcome', :on => :collection
    get 'inactive', :on => :collection
    get 'activity', :on => :collection
    get 'storage', :on => :collection
    post 'sudo', :on => :member
    post 'unsetup', :on => :member
    get 'setup_popup', :on => :member
    get 'profile', :on => :member
    post 'request_shell_access', :on => :member
    get 'virtual_machines', :on => :member
    get 'repositories', :on => :member
    get 'ssh_keys', :on => :member
    get 'link_account', :on => :collection
    post 'link_account', :on => :collection, :action => :merge
  end
  get '/current_token' => 'users#current_token'
  get "/add_ssh_key_popup" => 'users#add_ssh_key_popup', :as => :add_ssh_key_popup
  get "/add_ssh_key" => 'users#add_ssh_key', :as => :add_ssh_key
  resources :logs
  resources :factory_jobs
  resources :uploaded_datasets
  resources :groups do
    get 'choose', on: :collection
  end
  resources :specimens
  resources :pipeline_templates do
    get 'choose', on: :collection
  end
  resources :pipeline_instances do
    post 'cancel', :on => :member
    get 'compare', on: :collection
    post 'copy', on: :member
  end
  resources :links
  get '/collections/graph' => 'collections#graph'
  resources :collections do
    post 'set_persistent', on: :member
    get 'sharing_popup', :on => :member
    post 'share', :on => :member
    post 'unshare', :on => :member
    get 'choose', on: :collection
    post 'remove_selected_files', on: :member
    get 'tags', on: :member
    post 'save_tags', on: :member
    get 'multisite', on: :collection, to: redirect('/search')
  end
  get('/collections/download/:uuid/:reader_token/*file' => 'collections#show_file',
      format: false)
  get '/collections/download/:uuid/:reader_token' => 'collections#show_file_links'
  get '/collections/:uuid/*file' => 'collections#show_file', :format => false
  resources :projects do
    match 'remove/:item_uuid', on: :member, via: :delete, action: :remove_item
    match 'remove_items', on: :member, via: :delete, action: :remove_items
    get 'choose', on: :collection
    post 'share_with', on: :member
    get 'tab_counts', on: :member
    get 'public', on: :collection
  end

  resources :search do
    get 'choose', :on => :collection
  end

  resources :workflows

  get "trash" => 'trash_items#index', :as => :trash
  resources :trash_items do
    post 'untrash_items', on: :collection
  end

  post 'actions' => 'actions#post'
  get 'actions' => 'actions#show'
  get 'websockets' => 'websocket#index'
  post "combine_selected" => 'actions#combine_selected_files_into_collection'

  root :to => 'projects#index'

  match '/_health/ping', to: 'healthcheck#ping', via: [:get]

  get '/tests/mithril', to: 'tests#mithril'

  get '/status', to: 'status#status'

  # Send unroutable requests to an arbitrary controller
  # (ends up at ApplicationController#render_not_found)
  match '*a', to: 'links#render_not_found', via: [:get, :post]
end

apps/workbench/app/models/container_request.rb
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

class ContainerRequest < ArvadosBase
  def self.creatable?
    false
  end

  def textile_attributes
    [ 'description' ]
  end

  def self.goes_in_projects?
    true
  end

  def work_unit(label=nil, child_objects=nil)
    ContainerWorkUnit.new(self, label, self.uuid, child_objects=child_objects)
  end
end

apps/workbench/app/controllers/container_requests_controller.rb
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

class ContainerRequestsController < ApplicationController
  skip_around_action :require_thread_api_token, if: proc { |ctrl|
    !Rails.configuration.Users.AnonymousUserToken.empty? and
    'show' == ctrl.action_name
  }

  def generate_provenance(cr)
    return if params['tab_pane'] != "Provenance"

    nodes = {}
    child_crs = []
    col_uuids = []
    col_pdhs = []
    col_uuids << cr[:output_uuid] if cr[:output_uuid]
    col_pdhs += ProvenanceHelper::cr_input_pdhs(cr)

    # Search for child CRs
    if cr[:container_uuid]
      child_crs = ContainerRequest.where(requesting_container_uuid: cr[:container_uuid]).with_count("none")

      child_crs.each do |child|
        nodes[child[:uuid]] = child
        col_uuids << child[:output_uuid] if child[:output_uuid]
        col_pdhs += ProvenanceHelper::cr_input_pdhs(child)
      end
    end

    if nodes.length == 0
      nodes[cr[:uuid]] = cr
    end

    pdh_to_col = {} # Indexed by PDH
    output_pdhs = []

    # Batch requests to get all related collections
    # First fetch output collections by UUID.
    Collection.filter([['uuid', 'in', col_uuids.uniq]]).with_count("none").each do |c|
      output_pdhs << c[:portable_data_hash]
      pdh_to_col[c[:portable_data_hash]] = c
      nodes[c[:uuid]] = c
    end
    # Next, get input collections by PDH.
    Collection.filter(
      [['portable_data_hash', 'in', col_pdhs - output_pdhs]]).with_count("none").each do |c|
      nodes[c[:portable_data_hash]] = c
    end

    @svg = ProvenanceHelper::create_provenance_graph(
      nodes, "provenance_svg",
      {
        :request => request,
        :pdh_to_uuid => pdh_to_col,
      }
    )
  end

  def show_pane_list
    panes = %w(Status Log Provenance Advanced)
    if @object.andand.state == 'Uncommitted'
      panes = %w(Inputs) + panes - %w(Log Provenance)
    end
    panes
  end

  def show
    generate_provenance(@object)
    super
  end

  def cancel
    if @object.container_uuid
      c = Container.select(['state']).where(uuid: @object.container_uuid).with_count("none").first
      if c && c.state != 'Running'
        # If the container hasn't started yet, setting priority=0
        # leaves our request in "Committed" state and doesn't cancel
        # the container (even if no other requests are giving it
        # priority). To avoid showing this container request as "on
        # hold" after hitting the Cancel button, set state=Final too.
        @object.state = 'Final'
      end
    end
    @object.update_attributes! priority: 0
    if params[:return_to]
      redirect_to params[:return_to]
    else
      redirect_to @object
    end
  end

  def update
    @updates ||= params[@object.class.to_s.underscore.singularize.to_sym]
    input_obj = @updates[:mounts].andand[:"/var/lib/cwl/cwl.input.json"].andand[:content]
    if input_obj
      workflow = @object.mounts[:"/var/lib/cwl/workflow.json"][:content]
      get_cwl_inputs(workflow).each do |input_schema|
        if not input_obj.include? cwl_shortname(input_schema[:id])
          next
        end
        required, primary_type, param_id = cwl_input_info(input_schema)
        if input_obj[param_id] == ""
          input_obj[param_id] = nil
        elsif primary_type == "boolean"
          input_obj[param_id] = input_obj[param_id] == "true"
        elsif ["int", "long"].include? primary_type
          input_obj[param_id] = input_obj[param_id].to_i
        elsif ["float", "double"].include? primary_type
          input_obj[param_id] = input_obj[param_id].to_f
        elsif ["File", "Directory"].include? primary_type
          re = CollectionsHelper.match_uuid_with_optional_filepath(input_obj[param_id])
          if re
            c = Collection.find(re[1])
            input_obj[param_id] = {"class" => primary_type,
                                   "location" => "keep:#{c.portable_data_hash}#{re[4]}",
                                   "http://arvados.org/cwl#collectionUUID" => re[1]}
          end
        end
      end
    end
    params[:merge] = true
    begin
      super
    rescue => e
      flash[:error] = e.to_s
      show
    end
  end

  def copy
    src = @object

    @object = ContainerRequest.new

    # By default the copied CR won't be reusing containers, unless use_existing=true
    # param is passed.
    command = src.command
    if params[:use_existing]
      @object.use_existing = true
      # Pass the correct argument to arvados-cwl-runner command.
      if src.command[0] == 'arvados-cwl-runner'
        command = src.command - ['--disable-reuse']
        command.insert(1, '--enable-reuse')
      end
    else
      @object.use_existing = false
      # Pass the correct argument to arvados-cwl-runner command.
      if src.command[0] == 'arvados-cwl-runner'
        command = src.command - ['--enable-reuse']
        command.insert(1, '--disable-reuse')
      end
    end

    @object.command = command
    @object.container_image = src.container_image
    @object.cwd = src.cwd
    @object.description = src.description
    @object.environment = src.environment
    @object.mounts = src.mounts
    @object.name = src.name
    @object.output_path = src.output_path
    @object.priority = 1
    @object.properties[:template_uuid] = src.properties[:template_uuid]
    @object.runtime_constraints = src.runtime_constraints
    @object.scheduling_parameters = src.scheduling_parameters
    @object.state = 'Uncommitted'

    # set owner_uuid to that of source, provided it is a project and writable by current user
    current_project = Group.find(src.owner_uuid) rescue nil
    if (current_project && current_project.writable_by.andand.include?(current_user.uuid))
      @object.owner_uuid = src.owner_uuid
    end

    super
  end

  def index
    @limit = 20
    super
  end

end

apps/workbench/app/views/container_requests/_extra_tab_line_buttons.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<% if @object.state == 'Final' %>
<script type="application/javascript">
  function reset_form_cr_reuse() {
    $('#use_existing').removeAttr('checked');
  }
</script>

  <%= link_to raw('<i class="fa fa-fw fa-play"></i> Re-run...'),
      "#",
      {class: 'btn btn-sm btn-primary', 'data-toggle' => 'modal',
       'data-target' => '#clone-and-edit-modal-window',
       title: 'This will make a copy and take you there. You can then make any needed changes and run it'}  %>

<div id="clone-and-edit-modal-window" class="modal fade" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

    <%= form_tag copy_container_request_path do |f| %>

      <div class="modal-header">
        <button type="button" class="close" onClick="reset_form_cr_reuse()" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div>
          <div class="col-sm-6"> <h4 class="modal-title">Re-run container request</h4> </div>
        </div>
        <br/>
      </div>

      <div class="modal-body">
              <%= check_box_tag(:use_existing, "true", false) %>
              <%= label_tag(:use_existing, "Enable container reuse") %>
      </div>

      <div class="modal-footer">
        <button class="btn btn-default" onClick="reset_form_cr_reuse()" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button type="submit" class="btn btn-primary" name="container_request[state]" value="Uncommitted">Copy and edit inputs</button>
      </div>

    </div>
    <% end %>
  </div>
</div>

<% end %>

apps/workbench/app/views/container_requests/_name_and_description.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<%
  wu = @object.work_unit
  template_uuid = wu.template_uuid
  template = Workflow.find?(template_uuid) if template_uuid
  div_class = "col-sm-12"
  div_class = "col-sm-6" if template
%>

<div class="<%=div_class%>">
  <%= render partial: 'object_name' %>
  <%= render partial: 'object_description' %>
</div>

<% if template %>
  <div class="alert alert-info <%=div_class%>">
     This container request was created from the workflow <%= link_to_if_arvados_object template, friendly_name: true %><br />
     <% if template.modified_at && (template.modified_at > @object.created_at) %>
        Note: This workflow has been modified since this container request was created.
     <% end %>
  </div>
<% end %>

apps/workbench/app/views/container_requests/_show_inputs.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<%
n_inputs = if @object.mounts[:"/var/lib/cwl/workflow.json"] && @object.mounts[:"/var/lib/cwl/cwl.input.json"]
             cwl_inputs_required(@object, get_cwl_inputs(@object.mounts[:"/var/lib/cwl/workflow.json"][:content]), [:mounts, :"/var/lib/cwl/cwl.input.json", :content])
           else
             0
           end
%>

<% content_for :pi_input_form do %>
<form role="form" style="width:60%">
  <div class="form-group">
    <% workflow = @object.mounts[:"/var/lib/cwl/workflow.json"].andand[:content] %>
    <% if workflow %>
      <% inputs = get_cwl_inputs(workflow) %>
      <% inputs.each do |input| %>
        <label for="#input-<%= cwl_shortname(input[:id]) %>">
          <%= input[:label] || cwl_shortname(input[:id]) %>
        </label>
        <div>
          <p class="form-control-static">
            <%= render_cwl_input @object, input, [:mounts, :"/var/lib/cwl/cwl.input.json", :content] %>
          </p>
        </div>
        <p class="help-block">
          <%= input[:doc] %>
        </p>
      <% end %>
    <% end %>
  </div>
</form>
<% end %>

<% if n_inputs == 0 %>
  <p><i>This workflow does not need any further inputs specified.  Click the "Run" button at the bottom of the page to start the workflow.</i></p>
<% else %>
  <p><i>Provide <%= n_inputs > 1 ? 'values' : 'a value' %> for the following <%= n_inputs > 1 ? 'parameters' : 'parameter' %>, then click the "Run" button to start the workflow.</i></p>
<% end %>

<% if @object.editable? %>
  <%= content_for :pi_input_form %>
  <%= link_to(url_for('container_request[state]' => 'Committed'),
        class: 'btn btn-primary run-pipeline-button',
        method: :patch
        ) do %>
    Run <i class="fa fa-fw fa-play"></i>
  <% end %>
<% end %>

<%= render_unreadable_inputs_present %>

apps/workbench/app/views/container_requests/_show_log.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<%= render(partial: 'work_units/show_log', locals: {obj: @object, name: @object[:name] || 'this container'}) %>

apps/workbench/app/views/container_requests/_show_object_description_cell.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<div class="nowrap">
  <%= object.content_summary %><br />
  <%= render partial: 'container_requests/state_label', locals: {object: object} %>
</div>

apps/workbench/app/views/container_requests/_show_provenance.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<%= render partial: 'application/svg_div', locals: {
      divId: "provenance_graph",
      svgId: "provenance_svg",
      svg: @svg } %>

apps/workbench/app/views/container_requests/_show_recent.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<%= form_tag({}, {id: "containerRequests"}) do |f| %>

<table class="table table-condensed table-fixedlayout arv-recent-container-requests">
  <colgroup>
    <col width="10%" />
    <col width="20%" />
    <col width="20%" />
    <col width="15%" />
    <col width="15%" />
    <col width="15%" />
    <col width="5%" />
  </colgroup>
  <thead>
    <tr class="contain-align-left">
      <th>
        Status
      </th><th>
        Name
      </th><th>
        Description
      </th><th>
        Workflow
      </th><th>
        Owner
      </th><th>
        Created at
      </th><th>
      </th>
    </tr>
  </thead>

  <tbody data-infinite-scroller="#recent-container-requests" id="recent-container-requests"
         data-infinite-content-href="<%= url_for partial: :recent_rows %>" >
  </tbody>
</table>

<% end %>

apps/workbench/app/views/container_requests/_show_recent_rows.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<%
  containers = @objects.map(&:container_uuid).compact.uniq
  preload_objects_for_dataclass(Container, containers) if containers.any?

  workflows = @objects.collect {|o| o.properties[:template_uuid]}.compact.uniq
  preload_objects_for_dataclass(Workflow, workflows) if workflows.any?

  owner_uuids = @objects.map(&:owner_uuid).compact.uniq
  preload_objects_for_dataclass(User, owner_uuids) if owner_uuids.any?
  preload_objects_for_dataclass(Group, owner_uuids) if owner_uuids.any?

  objs = containers + workflows + owner_uuids
  preload_links_for_objects objs if objs.any?
%>

<% @objects.sort_by { |obj| obj.created_at }.reverse.each do |obj| %>
  <% wu = obj.work_unit obj.name %>

  <tr data-object-uuid="<%= wu.uuid %>" class="cr-<%= wu.uuid %>">
    <td>
      <span class="label label-<%= wu.state_bootstrap_class %>"><%= wu.state_label %></span>
    </td><td>
      <%= link_to_if_arvados_object obj, friendly_name: true, link_text: if obj.name && !obj.name.empty? then obj.name else obj.uuid end %>
    </td><td>
      <%= obj.description || '' %>
    </td><td>
      <%= link_to_if_arvados_object wu.template_uuid, friendly_name: true %>
    </td><td>
      <%= link_to_if_arvados_object wu.owner_uuid, friendly_name: true %>
    </td><td>
      <%= wu.created_at.to_s %>
    </td><td>
      <%= render partial: 'delete_object_button', locals: {object:obj} %>
    </td>
  </tr>
<% end %>

apps/workbench/app/views/container_requests/_show_status.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<%= render(partial: 'work_units/show_status', locals: {current_obj: @object, name: @object[:name] || 'this container'}) %>

apps/workbench/app/views/container_requests/_state_label.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<% wu = object.work_unit object.name %>
<span class="label label-<%=wu.state_bootstrap_class%>">
  <%=wu.state_label%>
</span>

apps/workbench/app/views/container_requests/index.html.erb
<%# Copyright (C) The Arvados Authors. All rights reserved.

SPDX-License-Identifier: AGPL-3.0 %>

<% content_for :tab_line_buttons do %>
  <div class="input-group">
    <input type="text" class="form-control filterable-control recent-container-requests-filterable-control"
           placeholder="Search container requests"
           data-filterable-target="#recent-container-requests"
           value="<%= params[:search] %>"
           />
  </div>
<% end %>

<%= render file: 'application/index.html.erb', locals: local_assigns %>